---
apiVersion : v1
kind: Service
metadata:
    name: order-ms-service
spec:
    type: LoadBalancer # since Nodeport is not working
    selector: 
        app: order-ms             
    ports:
        - protocol: TCP
          port: 80  # Port that the service exposes (can be different from the container port)
          targetPort: 8081 # Port that the service listens on inside the container
          nodePort: 30008 #(Port exposed on each node between 30000 and 32767)